export type UserRole = "admin" | "gerente" | "vendedor";
export interface Profile { id:string; full_name:string; role:UserRole; phone?:string|null; active:boolean; created_at?:string; }
export interface Customer { id:string; name:string; business_types:string[]|null; zone:string|null; city:string|null; address:string|null; phone:string|null; latitude:number|null; longitude:number|null; created_by:string|null; created_at?:string; }
export interface CustomerContact { id:string; customer_id:string; name:string; position:string|null; phone:string|null; whatsapp:string|null; email:string|null; is_decision_maker:"sí"|"no"|"parcialmente"|null; }
export interface CustomerProduct { id:string; customer_id:string; description:string; frequency:string|null; approx_quantity:number|null; unit:string|null; usual_brand:string|null; supplier:string|null; observations:string|null; }
export interface Category { id:string; name:string; }
export interface Product { id:string; category_id:string|null; sku:string; name:string; description:string|null; brand:string|null; unit:string|null; purchase_price:number|null; sale_price:number|null; image_url?:string|null; active:boolean; stock?:number; }
export interface ProductPrice { id:string; product_id:string; price_type:"minorista"|"mayorista"|"distribuidor"|"especial"; price:number; currency:string; active:boolean; }
export interface Visit { id:string; customer_id:string; user_id:string; visit_date:string; latitude:number|null; longitude:number|null; address:string|null; zone:string|null; photo_url:string|null; provider_name:string|null; provider_reasons:string[]|null; needs:string[]|null; need_description:string|null; purchase_timing:string|null; estimated_amount:number|null; interest_level:"Bajo"|"Medio"|"Alto"|null; result:string|null; opportunity_detected:boolean; opportunity_id:string|null; next_action_type:string|null; next_action_date:string|null; next_action_note:string|null; }
export interface Opportunity { id:string; customer_id:string; user_id:string; title:string; valor_estimado:number|null; probabilidad:number|null; estado:"detectada"|"en_negociacion"|"ganada"|"perdida"; created_at?:string; }
export interface FollowUp { id:string; customer_id:string; user_id:string; type:string; scheduled_date:string; completed:boolean; notes:string|null; }
export interface InventoryMovement { id:string; product_id:string; movement_type:"inicial"|"entrada"|"salida"|"ajuste_entrada"|"ajuste_salida"|"venta"; quantity:number; reference:string|null; notes:string|null; created_by:string|null; created_at:string; }
export interface Quotation { id:string; quotation_number:string; customer_id:string; user_id:string; quotation_date:string; valid_until:string|null; delivery_time:string|null; payment_terms:string|null; observations?:string|null; customer_address?:string|null; status:string; subtotal:number; discount:number; total:number; created_at:string; }
export interface QuotationItem { id:string; quotation_id:string; product_id:string; sku:string; description:string; brand?:string|null; unit?:string|null; quantity:number; unit_price:number; discount:number; subtotal:number; }
export interface Sale { id:string; sale_number:string; customer_id:string; user_id:string; quotation_id?:string|null; sale_date:string; customer_address?:string|null; payment_method:"Contado"|"Crédito"; delivery_time?:string|null; status:"borrador"|"confirmada"|"entregada"|"pagada"|"anulada"; subtotal:number; discount:number; total:number; amount_paid:number; balance:number; due_date?:string|null; observations?:string|null; created_at:string; }
export interface SaleItem { id:string; sale_id:string; product_id:string; sku:string; description:string; brand?:string|null; unit?:string|null; quantity:number; unit_price:number; purchase_cost:number; discount:number; subtotal:number; }

// Fase 9 — Proyectos
export type ProjectStatus = "registrado"|"cotizado"|"ganado"|"perdido"|"en_compra"|"facturado";
export interface Project { id:string; project_number:string; name:string; client_reference:string|null; customer_id:string; user_id:string; status:ProjectStatus; commission_percent:number|null; commission_amount:number; quotation_id:string|null; sale_id:string|null; observations:string|null; created_by:string|null; created_at:string; updated_at:string; }
export interface ProjectItem { id:string; project_id:string; product_id:string|null; client_item_code:string|null; client_description:string; internal_description:string|null; unit:string|null; requested_quantity:number; estimated_unit_cost:number; markup_percent:number|null; proposed_unit_price:number; created_at:string; }
export interface ProjectPurchase { id:string; project_id:string; supplier:string; purchase_date:string; has_invoice:boolean; invoice_number:string|null; invoice_amount:number|null; notes:string|null; created_by:string|null; created_at:string; }
export interface ProjectPurchaseItem { id:string; purchase_id:string; project_item_id:string|null; product_id:string; quantity:number; unit_cost:number; }
export type ProjectExpenseType = "transporte"|"insumos"|"comision"|"otro";
export interface ProjectExpense { id:string; project_id:string; expense_type:ProjectExpenseType; description:string; amount:number; has_invoice:boolean; invoice_number:string|null; created_by:string|null; created_at:string; }
export type ProjectDocumentType = "cotizacion_externa"|"factura_compra"|"factura_venta"|"otro";
export interface ProjectDocument { id:string; project_id:string; document_type:ProjectDocumentType; file_url:string; description:string|null; uploaded_by:string|null; uploaded_at:string; }
export interface ProjectProfitability { project_id:string; project_number:string; name:string; status:ProjectStatus; customer_name:string|null; total_ventas:number; compras_con_factura:number; compras_sin_factura:number; total_gastos:number; credito_fiscal:number; debito_fiscal:number; it:number; commission_amount:number; impuestos_a_pagar:number; utilidad_bruta:number; utilidad_neta:number; }
