import { useEffect, useState } from "react";
import { Layout } from "../components/Layout";
import { useAuth } from "../hooks/useAuth";
import { supabase } from "../lib/supabase";
import { Plus, Search, PackagePlus } from "lucide-react";

export function Inventario() {
  const { profile } = useAuth();
  const [productos,setProductos]=useState<any[]>([]); const [cats,setCats]=useState<any[]>([]); const [q,setQ]=useState("");
  const [open,setOpen]=useState(false); const [movement,setMovement]=useState<any>(null); const [error,setError]=useState("");
  const [form,setForm]=useState({sku:"",name:"",description:"",brand:"",category_id:"",unit:"unidad",purchase_price:"",sale_price:""});
  const [mov,setMov]=useState({product_id:"",movement_type:"entrada",quantity:"",reference:"",notes:""});
  const canEdit=profile?.role!=="vendedor";
  useEffect(()=>{load()},[profile]);
  async function load(){const [{data:c},{data:p}]=await Promise.all([supabase.from("categories").select("id,name").order("name"),supabase.from("product_inventory").select("*").order("name")]);setCats(c??[]);setProductos(p??[])}
  async function saveProduct(){setError("");const {error:e}=await supabase.from("products").insert({...form,purchase_price:Number(form.purchase_price)||0,sale_price:Number(form.sale_price)||0});if(e){setError(e.message);return}setOpen(false);setForm({sku:"",name:"",description:"",brand:"",category_id:"",unit:"unidad",purchase_price:"",sale_price:""});load()}
  async function saveMovement(){setError("");const {error:e}=await supabase.from("inventory_movements").insert({...mov,quantity:Number(mov.quantity),created_by:profile?.id});if(e){setError(e.message);return}setMovement(null);setMov({product_id:"",movement_type:"entrada",quantity:"",reference:"",notes:""});load()}
  const rows=productos.filter(p=>(p.name+" "+p.sku+" "+(p.brand||"")).toLowerCase().includes(q.toLowerCase()));
  return <Layout title="Inventario" subtitle="Productos, precios y existencias"><div className="space-y-4"><div className="flex gap-2"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#5B6670]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por código, producto o marca..." className="w-full pl-9 pr-3 py-2.5 rounded-xl border bg-white text-sm"/></div>{canEdit&&<button onClick={()=>setOpen(true)} className="px-4 py-2.5 rounded-xl bg-[#1B3A6B] text-white text-sm"><Plus size={15} className="inline mr-1"/>Producto</button>}</div>
  <div className="bg-white rounded-2xl p-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-[#5B6670] border-b"><th className="py-2">Código</th><th>Producto</th><th>Marca</th><th>Precio compra</th><th>Precio venta</th><th>Stock</th>{canEdit&&<th/>}</tr></thead><tbody>{rows.map(p=><tr key={p.product_id} className="border-b"><td className="py-2.5 font-mono text-xs">{p.sku}</td><td className="font-medium">{p.name}<div className="text-xs text-[#5B6670]">{p.description}</div></td><td>{p.brand||"—"}</td><td>Bs {Number(p.purchase_price||0).toFixed(2)}</td><td>Bs {Number(p.sale_price||0).toFixed(2)}</td><td className={`font-semibold ${Number(p.stock)<=0?"text-red-600":"text-[#3E7A56]"}`}>{p.stock} {p.unit||""}</td>{canEdit&&<td><button onClick={()=>{setMov(x=>({...x,product_id:p.product_id}));setMovement(true)}} className="text-xs text-[#1B3A6B]"><PackagePlus size={15}/></button></td>}</tr>)}</tbody></table></div>
  {open&&<Modal title="Nuevo producto" onClose={()=>setOpen(false)}><FormProduct form={form} setForm={setForm} cats={cats}/><button onClick={saveProduct} className="w-full py-2.5 rounded-xl bg-[#1B3A6B] text-white text-sm">Guardar producto</button></Modal>}
  {movement&&<Modal title="Movimiento de inventario" onClose={()=>setMovement(null)}><label className="text-xs">Tipo<select value={mov.movement_type} onChange={e=>setMov({...mov,movement_type:e.target.value})} className="w-full border rounded-xl p-2 mt-1 mb-2"><option value="inicial">Existencia inicial</option><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="ajuste_entrada">Ajuste entrada</option><option value="ajuste_salida">Ajuste salida</option></select></label><input type="number" min="0.01" placeholder="Cantidad" value={mov.quantity} onChange={e=>setMov({...mov,quantity:e.target.value})} className="w-full border rounded-xl p-2 mb-2"/><input placeholder="Referencia" value={mov.reference} onChange={e=>setMov({...mov,reference:e.target.value})} className="w-full border rounded-xl p-2 mb-2"/><input placeholder="Observaciones" value={mov.notes} onChange={e=>setMov({...mov,notes:e.target.value})} className="w-full border rounded-xl p-2 mb-3"/><button onClick={saveMovement} className="w-full py-2.5 rounded-xl bg-[#1B3A6B] text-white text-sm">Registrar movimiento</button></Modal>}
  {error&&<div className="text-sm text-red-600">{error}</div>}</div></Layout>
}
function FormProduct({form,setForm,cats}:any){const p=(k:string,v:string)=>setForm((x:any)=>({...x,[k]:v}));return <div className="space-y-2 mb-3">{[["sku","Código SACIPETROL"],["name","Descripción / nombre"],["brand","Marca"],["description","Especificaciones"],["unit","Unidad"],["purchase_price","Precio de compra"],["sale_price","Precio de venta"]].map(([k,l])=><input key={k} placeholder={l} value={form[k]} onChange={e=>p(k,e.target.value)} className="w-full border rounded-xl p-2.5 text-sm"/>)}<select value={form.category_id} onChange={e=>p("category_id",e.target.value)} className="w-full border rounded-xl p-2.5 text-sm"><option value="">Sin categoría</option>{cats.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>}
function Modal({title,onClose,children}:any){return <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl p-5 w-full max-w-lg"><div className="flex justify-between mb-4"><h2 className="font-semibold text-[#0F2647]">{title}</h2><button onClick={onClose}>✕</button></div>{children}</div></div>}
